import { useEffect, useState, useRef } from 'react';
import * as Dropdown from '@radix-ui/react-dropdown-menu';
import { X, Plus, Link2, MoreHorizontal, Check, History, Pencil, Flag, CircleHelp, Camera, Scan, ArrowUpRight, LoaderCircle, FileText, Image, Mic, Video, ChevronRight } from 'lucide-react';
import { toast } from 'sonner';
import { Avatar, Modal, formatDate } from './ui';
import { FactForm, RelationForm } from './PeopleForms';
import { api, json, upload } from '../api';
import { formatFamilyDate, isDateFact } from '../../shared/person-fields';
import { FACT_LABELS, type AppState, type Fact, type Relation, type FactKey, type Reviewed, type HistoryEntry } from '../../shared/types';

export function ReviewBadge({item}:{item:Reviewed}) {return <span className={`badge status-${item.status}`}>{item.status==='confirmed'?<Check size={11}/>:item.status==='disputed'?<Flag size={11}/>:<span className="status-dot"/>}{item.status==='confirmed'?'Подтверждено':item.status==='disputed'?'Есть разногласие':'Не подтверждено'}</span>;}
export default function PersonPanel({state,personId,onClose,onRefresh,onSelect,onAddRelative,onFocus,onArchive}:{state:AppState;personId:string;onClose:()=>void;onRefresh:()=>Promise<void>;onSelect:(id:string)=>void;onAddRelative:()=>void;onFocus:()=>void;onArchive:()=>void}) {
 const person=state.people.find(p=>p.id===personId)!;const facts=state.facts.filter(f=>f.personId===personId);const relations=state.relations.filter(r=>r.fromId===personId||r.toId===personId);const materials=state.materials.filter(m=>m.personIds.includes(personId));const canWrite=state.user.role!=='viewer';
 const [factEdit,setFactEdit]=useState<Fact|true|null>(null);const [relationEdit,setRelationEdit]=useState<Relation|true|null>(null);const [history,setHistory]=useState<HistoryEntry[]|null>(null);const [dispute,setDispute]=useState<{kind:string;item:Reviewed}|null>(null);const [note,setNote]=useState('');const [busy,setBusy]=useState(false);const photoInput=useRef<HTMLInputElement>(null);const closeButton=useRef<HTMLButtonElement>(null);
 useEffect(()=>{const previous=document.activeElement as HTMLElement|null;closeButton.current?.focus({preventScroll:true});return()=>{if(previous&&document.contains(previous))previous.focus({preventScroll:true});};},[personId]);
 useEffect(()=>{setFactEdit(null);setRelationEdit(null);setHistory(null);setDispute(null);},[personId]);
 const author=(id:string|null)=>state.users.find(u=>u.id===id)?.name||'Участник семьи';const remaining=(Object.keys(FACT_LABELS) as FactKey[]).filter(k=>!facts.some(f=>f.key===k));const editable=(item:Reviewed)=>canWrite&&(state.user.role==='admin'||item.createdBy===state.user.id);
 async function review(kind:string,item:Reviewed,action:'confirm'|'dispute',text?:string){setBusy(true);try{await api(`/api/review/${kind}/${item.id}`,json('POST',{action,version:item.version,note:text}));await onRefresh();setDispute(null);toast.success(action==='confirm'?'Сведение подтверждено':'Неточность отмечена');}catch(e){toast.error((e as Error).message);}finally{setBusy(false);}}
 async function viewHistory(kind:string,item:Reviewed){try{setHistory(await api<HistoryEntry[]>(`/api/history/${kind}/${item.id}`));}catch(e){toast.error((e as Error).message);}}
 function actions(kind:string,item:Reviewed,onEdit:()=>void){return <Dropdown.Root><Dropdown.Trigger asChild><button className="icon-button small" aria-label="Действия со сведением"><MoreHorizontal size={18}/></button></Dropdown.Trigger><Dropdown.Portal><Dropdown.Content className="dropdown" sideOffset={5} align="end">{canWrite&&item.updatedBy!==state.user.id&&item.status==='unconfirmed'&&<Dropdown.Item className="dropdown-item" onSelect={()=>review(kind,item,'confirm')}><Check size={16}/>Подтвердить</Dropdown.Item>}{editable(item)&&<Dropdown.Item className="dropdown-item" onSelect={onEdit}><Pencil size={16}/>Изменить</Dropdown.Item>}{canWrite&&<Dropdown.Item className="dropdown-item" onSelect={()=>{setNote('');setDispute({kind,item});}}><Flag size={16}/>Есть неточность</Dropdown.Item>}<Dropdown.Item className="dropdown-item" onSelect={()=>viewHistory(kind,item)}><History size={16}/>История изменений</Dropdown.Item></Dropdown.Content></Dropdown.Portal></Dropdown.Root>;}
 async function changePhoto(file?:File){if(!file)return;setBusy(true);try{const uploaded=await upload(file);await api(`/api/people/${personId}`,json('PATCH',{avatarFileId:uploaded.id}));await onRefresh();toast.success('Фотография сохранена');}catch(e){toast.error((e as Error).message);}finally{setBusy(false);}}
 function describeHistory(entry:HistoryEntry) {
  try {const after=JSON.parse(entry.after||'{}');const before=JSON.parse(entry.before||'null');let detail='';
   if(after.key&&after.value!==undefined){const label=FACT_LABELS[after.key as FactKey]||'Сведение';detail=`${label}: ${before?.value&&before.value!==after.value?`${before.value} → `:''}${after.value}`;}
   else if(after.fromId){const name=(id:string)=>state.people.find(p=>p.id===id)?.name||'Человек';detail=after.type==='partner'?`${name(after.fromId)} и ${name(after.toId)} — партнёры`:`${name(after.fromId)} — родитель ${name(after.toId)}`;}
   return [detail,after.source?`Источник: ${after.source}`:'',after.disputeNote?`Неточность: ${after.disputeNote}`:''].filter(Boolean).join('\n');
  } catch {return 'Подробности недоступны';}
 }
 const materialIcon={story:FileText,photo:Image,audio:Mic,video:Video};
 return <aside className="person-panel" aria-label={`Карточка: ${person.name}`}><div className="panel-toolbar"><span>Карточка человека</span><button ref={closeButton} className="icon-button" onClick={onClose} aria-label="Закрыть карточку"><X size={19}/></button></div><div className="panel-scroll"><div className="person-hero"><div className="profile-photo"><Avatar name={person.name} fileId={person.avatarFileId} size={88}/>{canWrite&&(state.user.role==='admin'||person.createdBy===state.user.id)&&<><button className="photo-edit" aria-label="Изменить фотографию" onClick={()=>photoInput.current?.click()} disabled={busy}><Camera size={14}/></button><input ref={photoInput} type="file" accept="image/jpeg,image/png,image/webp,image/heic,image/heif" hidden onChange={e=>changePhoto(e.target.files?.[0])}/></>}</div><h2>{person.name}</h2><p>{[facts.find(f=>f.key==='birthDate')?.value,facts.find(f=>f.key==='deathDate')?.value].filter((value): value is string=>Boolean(value)).map(formatFamilyDate).join(' — ')||'Даты пока не указаны'}</p><button className="button subtle compact" onClick={onFocus}><Scan size={15}/>Показать близких</button></div>
 <section className="profile-section"><div className="section-heading"><h3>Сведения</h3>{canWrite&&remaining.length>0&&<button className="text-button" onClick={()=>setFactEdit(true)}><Plus size={15}/>Добавить</button>}</div>{facts.map(f=><div className="fact-item" key={f.id}><div className="fact-top"><span className="eyebrow">{FACT_LABELS[f.key]}</span>{actions('facts',f,()=>setFactEdit(f))}</div><p className="fact-value">{isDateFact(f.key) ? formatFamilyDate(f.value) : f.value}</p><div className="fact-review"><ReviewBadge item={f}/>{f.status==='confirmed'&&<small>{author(f.confirmedBy)}</small>}</div><div className="fact-provenance"><span>{f.version>1?'Изменил(а)':'Добавил(а)'} {author(f.updatedBy)}</span>{f.source&&<span>{f.source}</span>}{f.sourceQuote&&<blockquote>{f.sourceQuote}</blockquote>}{f.sourceMaterialId&&<button className="text-button" onClick={onArchive}>Открыть архив с источником <ArrowUpRight size={12}/></button>}{f.disputeNote&&<p className="dispute-note">{f.disputeNote}</p>}</div>{canWrite&&f.updatedBy!==state.user.id&&f.status==='unconfirmed'&&<button className="verify-button" disabled={busy} onClick={()=>review('facts',f,'confirm')}><Check size={14}/>Подтвердить</button>}</div>)}</section>
 <section className="profile-section"><div className="section-heading"><h3>Родные</h3>{canWrite&&<Dropdown.Root><Dropdown.Trigger asChild><button className="text-button"><Plus size={15}/>Добавить</button></Dropdown.Trigger><Dropdown.Portal><Dropdown.Content className="dropdown" align="end" sideOffset={6}><Dropdown.Item className="dropdown-item" onSelect={onAddRelative}><Plus size={16}/>Нового человека</Dropdown.Item><Dropdown.Item className="dropdown-item" onSelect={()=>setRelationEdit(true)}><Link2 size={16}/>Связь с человеком в дереве</Dropdown.Item></Dropdown.Content></Dropdown.Portal></Dropdown.Root>}</div>{relations.length?relations.map(r=>{const otherId=r.fromId===personId?r.toId:r.fromId;const other=state.people.find(p=>p.id===otherId);if(!other)return null;return <div className="relative-row" key={r.id}><button className="relative-main" onClick={()=>onSelect(otherId)}><Avatar name={other.name} fileId={other.avatarFileId} size={38}/><span><strong>{other.name}</strong><small>{r.type==='partner'?'Партнёр':r.fromId===personId?'Ребёнок':'Родитель'}{r.type==='parent'&&r.parentKind==='adoptive'?' · усыновление':''}</small></span><ChevronRight size={15}/></button><div className="relative-review"><ReviewBadge item={r}/>{actions('relations',r,()=>setRelationEdit(r))}</div>{r.disputeNote&&<p className="dispute-note">{r.disputeNote}</p>}</div>}):<div className="inline-empty"><Link2 size={21}/><p>Родственные связи пока не добавлены.</p></div>}</section>
 <section className="profile-section"><div className="section-heading"><h3>Истории и материалы</h3><button className="text-button" onClick={onArchive}>{materials.length?'Все':'Открыть архив'}<ArrowUpRight size={14}/></button></div>{materials.length?materials.slice(0,3).map(m=>{const Icon=materialIcon[m.kind];return <button className="person-material" key={m.id} onClick={onArchive}>{m.kind==='photo'&&m.file?<img src={m.file.url} alt=""/>:<span className="material-mini-icon"><Icon size={21}/></span>}<span><strong>{m.title}</strong><small>{formatDate(m.occurredAt||m.createdAt)}</small></span><ChevronRight size={15}/></button>}):<div className="inline-empty"><FileText size={22}/><p>Здесь появятся связанные истории, фотографии и записи.</p></div>}</section><p className="profile-created">Карточку добавил(а) {author(person.createdBy)}<br/>{formatDate(person.createdAt)}</p></div>
 {factEdit&&<FactForm personId={personId} fact={factEdit===true?undefined:factEdit} availableKeys={remaining} onClose={()=>setFactEdit(null)} onSaved={onRefresh}/>}{relationEdit&&<RelationForm state={state} personId={personId} relation={relationEdit===true?undefined:relationEdit} onClose={()=>setRelationEdit(null)} onSaved={onRefresh}/>}
 {dispute&&<Modal open onClose={()=>setDispute(null)} title="Уточнить сведение"><form className="form-stack" onSubmit={e=>{e.preventDefault();review(dispute.kind,dispute.item,'dispute',note);}}><p className="muted">Расскажите, в чём неточность. Ваше пояснение будет видно семье.</p><label className="field">Пояснение<textarea autoFocus rows={4} required value={note} maxLength={2000} onChange={e=>setNote(e.target.value)}/></label><div className="form-actions"><button type="button" className="button secondary" onClick={()=>setDispute(null)}>Отмена</button><button className="button primary" disabled={busy||!note.trim()}>Сохранить</button></div></form></Modal>}
 {history&&<Modal open onClose={()=>setHistory(null)} title="История изменений"><div className="history-list">{history.length?[...history].reverse().map(h=><div className="history-row" key={h.id}><History size={16}/><div><strong>{author(h.actorId)}</strong><span>{({create:'Добавлено',update:'Изменено',edit:'Изменено',accept_proposal:'Принято из записи',confirm:'Подтверждено',dispute:'Отмечена неточность'} as Record<string,string>)[h.action]||h.action}</span>{h.after&&<details><summary>Содержание изменения</summary><p className="history-content">{describeHistory(h)}</p></details>}<small>{formatDate(h.createdAt)}</small></div></div>):<p className="muted">Изменений пока нет.</p>}</div></Modal>}
 </aside>;
}
